name: Node CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    # Install dependencies
    - run: npm ci
    # Make sure that it can build
    - run: npm run build
